# Generated by Django 3.2.11 on 2024-12-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='disco_duro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='sistema_operativo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
